### ISSUE TITLE
Thanks for giving credit, I can help give you some hacks if you want,

### ISSUE THREAD

**Issue by Hankypoo7** [pazza223/blooket-hack-colection#1]
yea pretty much the title but also I totally understand if it's a no, but if you added me as a contributor I can make it more oranised too

**Comment by pazza223** [comment]
yes please, but i do not know how to add contributor, can you give me steps and i will do it. also i will rely apreshiate the extra hacks. also (not related) do you know how to get around the thyme multitool evry day update? just asking becuse you seem to probaly know more. i just wanted a quick way to give people blooket hacks, more hacks, orginized wold be amazing and i wold apritiate it!

**Comment by pazza223** [comment]
@Hankypoo7 yes please, but i do not know how to add contributor, can you give me steps and i will do it. also i will rely apreshiate the extra hacks. also (not related) do you know how to get around the thyme multitool evry day update? just asking becuse you seem to probaly know more. i just wanted a quick way to give people blooket hacks, more hacks, orginized wold be amazing and i wold apritiate it!
