### ISSUE TITLE
Remove BlooketUI

### ISSUE THREAD

**Issue by ZasticBradyn** [pazza223/blooket-hack-colection#2]
hey sorry to open a issue, but [BlooketUI](https://github.com/ZasticBradyn/BlooketUI) has been discountied please remove it from your list of hacks thanks.<br><p>- zastix</p>

**Comment by pazza223** [comment]
fixed it. thanks for leting me know. i only remove hacks when thay stop working for me. it was working fine for me. also if you find eny hacks that are not working please let me know!

**Comment by ZasticBradyn** [comment]
I will, thanks for removing it.
